#!/bin/bash

local programs='zsh git rcm'

# macOS
if command -v brew &>/dev/null; then
    brew install $programs

# linux (with apt)
elif command -v apt &>/dev/null; then
    sudo apt update -y
    sudo apt install $programs wget -y

# something else (probably windows)
else
    echo "No package manager recognized. Install these things yourself: $programs"
fi

# oh-my-zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# zsh auto-suggestions
git clone https://github.com/zsh-users/zsh-autosuggestions ~/.zsh/zsh-autosuggestions

# zsh syntax highlighting
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git

# fzf
git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
~/.fzf/install --all
