#!/bin/bash

programs='zsh git rcm neovim'

# macOS
if command -v brew &>/dev/null; then
    brew install $programs

# linux (with apt)
elif command -v apt &>/dev/null; then
    sudo apt update -y
    sudo apt install $programs wget -y

# something else (probably windows)
else
    echo "No package manager recognized. Install these things yourself: $programs"
fi

# packer
git clone --depth 1 https://github.com/wbthomason/packer.nvim $HOME/.local/share/nvim/site/pack/packer/start/packer.nvim

# oh-my-zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# zsh auto-suggestions
git clone https://github.com/zsh-users/zsh-autosuggestions $HOME/.zsh/zsh-autosuggestions

# zsh syntax highlighting
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git $HOME/.zsh/zsh-syntax-highlighting

# fzf
git clone --depth 1 https://github.com/junegunn/fzf.git $HOME/.fzf
$HOME/.fzf/install --key-bindings --completion --no-update-rc

# zsh nvm lazy load
git clone https://github.com/lukechilds/zsh-nvm $ZSH/custom/plugins/zsh-nvm

# nvm
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | PROFILE=/dev/null bash -s
